<?php

namespace BaskelBundle\Repository;

/**
 * PanierLigneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PanierLigneRepository extends \Doctrine\ORM\EntityRepository
{
}
