<?php

namespace BaskelBundle\Repository;

/**
 * WishRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WishRepository extends \Doctrine\ORM\EntityRepository
{
}
